import { processObservationListStellarium } from "@/lib/observation_lists_utils";
import { StellariumObservationObject, ObservationObject } from "@/types";

describe("processObservationListStellarium", () => {
  it("formats and sorts a list of observation objects", () => {
    let observations: StellariumObservationObject[] = [
      {
        constellation: "CMa",
        dec: "-20°45'32\"",
        designation: "M 41",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "4.50",
        name: "Little Beehive Cluster",
        nameI18n: "Little Beehive Cluster",
        objtype: "open star cluster",
        ra: "6h45m59.8s",
        type: "Nebula",
      },
      {
        constellation: "Cyg",
        dec: "+30°42'18\"",
        designation: "C 34",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "7.00",
        name: "Filamentary Nebula",
        nameI18n: "Filamentary Nebula",
        objtype: "supernova remnant",
        ra: "20h45m38.7s",
        type: "Nebula",
      },
      {
        constellation: "Cas",
        dec: "+61°26'50\"",
        designation: "IC 1805",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "6.50",
        name: "Heart Nebula",
        nameI18n: "Heart Nebula",
        objtype: "cluster associated with nebulosity",
        ra: "2h32m39.6s",
        type: "Nebula",
      },
      {
        constellation: "Ori",
        dec: "-2°30'04\"",
        designation: "IC 434",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "7.30",
        name: "Horsehead Nebula",
        nameI18n: "Horsehead Nebula",
        objtype: "HII region",
        ra: "5h40m46.7s",
        type: "Nebula",
      },
      {
        constellation: "Sco",
        dec: "-32°15'10\"",
        designation: "M 6",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "4.20",
        name: "Butterfly Cluster",
        nameI18n: "Butterfly Cluster",
        objtype: "open star cluster",
        ra: "17h40m21.4s",
        type: "Nebula",
      },
      {
        constellation: "Ari",
        dec: "+11°16'08\"",
        designation: "Jupiter",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "-2.09",
        name: "Jupiter",
        nameI18n: "Jupiter",
        objtype: "planet",
        ra: "2h02m08.0s",
        type: "Planet",
      },
      {
        constellation: "Leo",
        dec: "+13°05'33\"",
        designation: "M 65",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "9.30",
        name: "Leo Triplet",
        nameI18n: "Leo Triplet",
        objtype: "galaxy",
        ra: "11h18m56.2s",
        type: "Nebula",
      },

      {
        constellation: "Cyg",
        dec: "+31°44'22\"",
        designation: "C 33",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "7.00",
        name: "East Veil Nebula",
        nameI18n: "East Veil Nebula",
        objtype: "supernova remnant",
        ra: "20h56m19.6s",
        type: "Nebula",
      },
      {
        constellation: "Dor",
        dec: "-69°45'27\"",
        designation: "PGC 17223",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "0.90",
        name: "Large Magellanic Cloud",
        nameI18n: "Large Magellanic Cloud",
        objtype: "galaxy",
        ra: "5h23m31.2s",
        type: "Nebula",
      },
      {
        constellation: "Gem",
        dec: "+24°21'08\"",
        designation: "Venus",
        fov: 0,
        isVisibleMarker: true,
        jd: 0,
        landscapeID: "",
        location: "",
        magnitude: "-4.34",
        name: "Venus",
        nameI18n: "Venus",
        objtype: "planet",
        ra: "7h36m33.8s",
        type: "Planet",
      },
    ];
    let expected: ObservationObject[] = [
      {
        dec: "+11°16'08\"",
        designation: "Jupiter",
        displayName: "Jupiter",
        magnitude: "-2.09",
        type: "planet",
        typeCategory: "solar_system",
        ra: "2h02m08.0s",
        catalogue: "Jupiter",
        objectNumber: -1,
        constellation: "Aries",
      },
      {
        dec: "+24°21'08\"",
        designation: "Venus",
        displayName: "Venus",
        magnitude: "-4.34",
        type: "planet",
        typeCategory: "solar_system",
        ra: "7h36m33.8s",
        catalogue: "Venus",
        objectNumber: -1,
        constellation: "Gemini",
      },
      {
        dec: "+31°44'22\"",
        designation: "C 33",
        displayName: "C 33 - East Veil Nebula",
        magnitude: "7.00",
        type: "supernova remnant",
        typeCategory: "nebulae",
        ra: "20h56m19.6s",
        catalogue: "C",
        objectNumber: 33,
        constellation: "Cygnus",
      },
      {
        dec: "+30°42'18\"",
        designation: "C 34",
        displayName: "C 34 - Filamentary Nebula",
        magnitude: "7.00",
        type: "supernova remnant",
        typeCategory: "nebulae",
        ra: "20h45m38.7s",
        catalogue: "C",
        objectNumber: 34,
        constellation: "Cygnus",
      },
      {
        dec: "-2°30'04\"",
        designation: "IC 434",
        displayName: "IC 434 - Horsehead Nebula",
        magnitude: "7.30",
        type: "HII region",
        typeCategory: "nebulae",
        ra: "5h40m46.7s",
        catalogue: "IC",
        objectNumber: 434,
        constellation: "Orion",
      },
      {
        dec: "+61°26'50\"",
        designation: "IC 1805",
        displayName: "IC 1805 - Heart Nebula",
        magnitude: "6.50",
        type: "cluster associated with nebulosity",
        typeCategory: "nebulae",
        ra: "2h32m39.6s",
        catalogue: "IC",
        objectNumber: 1805,
        constellation: "Cassiopeia",
      },
      {
        dec: "-32°15'10\"",
        designation: "M 6",
        displayName: "M 6 - Butterfly Cluster",
        magnitude: "4.20",
        type: "open star cluster",
        typeCategory: "clusters",
        ra: "17h40m21.4s",
        catalogue: "M",
        objectNumber: 6,
        constellation: "Scorpius",
      },
      {
        dec: "-20°45'32\"",
        designation: "M 41",
        displayName: "M 41 - Little Beehive Cluster",
        magnitude: "4.50",
        type: "open star cluster",
        typeCategory: "clusters",
        ra: "6h45m59.8s",
        catalogue: "M",
        objectNumber: 41,
        constellation: "Canis Major",
      },
      {
        dec: "+13°05'33\"",
        designation: "M 65",
        displayName: "M 65 - Leo Triplet",
        magnitude: "9.30",
        type: "galaxy",
        typeCategory: "galaxies",
        ra: "11h18m56.2s",
        catalogue: "M",
        objectNumber: 65,
        constellation: "Leo",
      },
      {
        dec: "-69°45'27\"",
        designation: "PGC 17223",
        displayName: "PGC 17223 - Large Magellanic Cloud",
        magnitude: "0.90",
        type: "galaxy",
        typeCategory: "galaxies",
        ra: "5h23m31.2s",
        catalogue: "PGC",
        objectNumber: 17223,
        constellation: "Dorado",
      },
    ];

    let res = processObservationListStellarium(observations);
    expect(res).toEqual(expected);
  });
});
