name: Build and Release

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
          cp -r dist DwarfStellariumGoto
          echo "python3 -m http.server" > DwarfStellariumGoto/start_server.bat
          tar -czvf DwarfStellariumGoto.tar.gz DwarfStellariumGoto
          rm -rf DwarfStellariumGoto

      - name: Get version number from version.txt
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: DwarfStellariumGoto-${{ steps.get_version.outputs.version }}
          path: DwarfStellariumGoto.tar.gz
    
      - name: Release with ncipollo/release-action
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: DwarfStellariumGoto.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
          tag: v${{ steps.get_version.outputs.version }}
    